apiVersion: v1
kind: Service
metadata:
  name: exchange
spec:
  selector:
    app: exchange
  ports:
    - port: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: exchange-deployment
spec:
  replicas: 1
  strategy: {}
  selector:
    matchLabels:
      app: exchange      
  template:
    metadata:
      labels:
        app: exchange
    spec:
      containers:
        - name: exchange
          image: {{ .Values.images.exchange }}
          ports:
            - containerPort: 80
          env:
            - name: BINANCE_TESTNET
              value: "{{ .Values.env.exchange.BINANCE_TESTNET }}"
            - name: BINANCE_API_KEY
              value: "{{ .Values.env.exchange.BINANCE_API_KEY }}"
            - name: BINANCE_SECRET_KEY
              value: "{{ .Values.env.exchange.BINANCE_SECRET_KEY }}"
            - name: NATS_URL
              value: "{{ .Values.env.exchange.NATS_URL }}"
            - name: NATS_USER
              value: "{{ .Values.env.nats.USER }}"
            - name: NATS_PASS
              value: "{{ .Values.env.nats.PASS }}"
            - name: DATABASE_URL
              value: "{{ .Values.env.exchange.DATABASE_URL }}"
